version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
      day: "monday"
      time: "12:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: ":arrow_up: deps:"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "12:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: ":package: deps:"
